---
apiVersion: v1
kind: Service
metadata:
  name: infinispan-service-http
  namespace: {{ .Release.Namespace }}
  labels:
    app: infinispan-service-http
spec:
  ports:
    - name: infinispan-service-http-port
      port: 11222
      protocol: TCP
      targetPort: 11222
  selector:
    app: infinispan-deployment
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: infinispan-service-ping
  labels:
    app: infinispan-service-ping
spec:
  publishNotReadyAddresses: true
  ports:
    - name: infinispan-service-ping-port
      port: 8888
      protocol: TCP
      targetPort: 8888
  selector:
    app: infinispan-deployment
  # Create as a headless service by specifying ClusterIP with clusterIp: None
  # This will allow the pods to connect to pods directly without load balancing or proxying
  type: ClusterIP
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: infinispan-service-metrics
  labels:
    app: infinispan-service-metrics
spec:
  ports:
    - name: infinispan-service-metrics-port
      port: 11223
      protocol: TCP
      targetPort: 11223
  selector:
    app: infinispan-deployment
  type: NodePort