apiVersion: v1
kind: Secret
metadata:
  name: infinispan-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: infinispan-secret
type: Opaque
stringData:
  username: ${infinispan.monitor.username}
  password: ${infinispan.monitor.password}
  identities-batch: |-
    user create ${infinispan.developer.username} -p ${infinispan.developer.password} -g admin
    user create ${infinispan.observer.username} -p ${infinispan.observer.password} -g observer
    user create ${infinispan.keycloak.username} -p ${infinispan.keycloak.password} -g application
    user create ${infinispan.monitor.username} -p ${infinispan.monitor.password} --users-file metrics-users.properties --groups-file metrics-groups.properties
