apiVersion: v1
kind: Secret
metadata:
  name: infinispan-identities-batch-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: infinispan-identities-batch-secret
type: Opaque
stringData:
  identities-batch: |-
    user create {{ include "getIspnSecret" (dict "NS" .Release.Namespace "Secret" .Values.infinispan.externalKubernetesSecret.name "Key" "ISPN_DEVELOPER_USERNAME")  }} -p {{ include "getIspnSecret" (dict "NS" .Release.Namespace "Secret" .Values.infinispan.externalKubernetesSecret.name "Key" "ISPN_DEVELOPER_PASSWORD")  }} -g admin
    user create {{ include "getIspnSecret" (dict "NS" .Release.Namespace "Secret" .Values.infinispan.externalKubernetesSecret.name "Key" "ISPN_OBSERVER_USERNAME")  }} -p {{ include "getIspnSecret" (dict "NS" .Release.Namespace "Secret" .Values.infinispan.externalKubernetesSecret.name "Key" "ISPN_OBSERVER_PASSWORD")  }} -g observer
    user create {{ include "getIspnSecret" (dict "NS" .Release.Namespace "Secret" .Values.infinispan.externalKubernetesSecret.name "Key" "ISPN_KEYCLOAK_USERNAME")  }} -p {{ include "getIspnSecret" (dict "NS" .Release.Namespace "Secret" .Values.infinispan.externalKubernetesSecret.name "Key" "ISPN_KEYCLOAK_PASSWORD")  }} -g application
    user create {{ include "getIspnSecret" (dict "NS" .Release.Namespace "Secret" .Values.infinispan.externalKubernetesSecret.name "Key" "ISPN_MONITOR_USERNAME")  }} -p {{ include "getIspnSecret" (dict "NS" .Release.Namespace "Secret" .Values.infinispan.externalKubernetesSecret.name "Key" "ISPN_MONITOR_PASSWORD")  }} --users-file metrics-users.properties --groups-file metrics-groups.properties
