apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: keycloak-secret
type: Opaque
stringData:
  KEYCLOAK_ADMIN: {{ .Values.keycloak.admin.username }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.keycloak.admin.password }}
  KC_DB_USERNAME: {{ .Values.keycloak.database.username }}
  KC_DB_PASSWORD: {{ .Values.keycloak.database.password }}
  KC_CACHE_REMOTE_STORE_USERNAME: {{ .Values.keycloak.infinispan.username }}
  KC_CACHE_REMOTE_STORE_PASSWORD: {{ .Values.keycloak.infinispan.password }}