---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak-infinispan-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    # The name of your reserved IP address
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.ingress.globalStaticIpName }}
    networking.gke.io/managed-certificates: keycloak-infinispan-managed-cert
    ingressClassName: "gce"
spec:
  rules:
    - host: keycloak.paulhowells.dev
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: keycloak-service-http
                port:
                  number: 8080
    - host: infinispan.paulhowells.dev
      http:
        paths:
          - path: /console
            pathType: ImplementationSpecific
            backend:
              service:
                name: infinispan-service-http
                port:
                  number: 11222
          - path: /console/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: infinispan-service-http
                port:
                  number: 11222
          - path: /rest/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: infinispan-service-http
                port:
                  number: 11222
          - path: /metrics
            pathType: ImplementationSpecific
            backend:
              service:
                name: infinispan-service-metrics
                port:
                  number: 11223
          - path: /metrics/
            pathType: ImplementationSpecific
            backend:
              service:
                name: infinispan-service-metrics
                port:
                  number: 11223