apiVersion: v1
kind: Secret
metadata:
  name: keycloak-configurer-job-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: keycloak-configurer-job-secret
type: Opaque
stringData:
  MASTER_REALM_ADMIN_USERNAME: {{ .Values.keycloak.admin.username }}
  MASTER_REALM_ADMIN_PASSWORD: {{ .Values.keycloak.admin.password }}