---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-service-http
  namespace: {{ .Release.Namespace }}
  labels:
    app: keycloak-service-http
spec:
  ports:
    - name: keycloak-service-http-port
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: keycloak-deployment
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-jgroups-ping
  labels:
    app: keycloak-jgroups-ping
spec:
  publishNotReadyAddresses: true
  ports:
    - name: keycloak-jgroups-ping-port
      port: 7800
      protocol: TCP
      targetPort: 7800
  selector:
    app: keycloak-deployment
  # Create as a headless service by specifying ClusterIP with clusterIp: None
  # This will allow the pods to connect to pods directly without load balancing or proxying
  type: ClusterIP
  clusterIP: None