apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume-claim
  namespace: {{ .Release.Namespace }}
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 1Gi