apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-deployment
  template:
    metadata:
      labels:
        app: postgres-deployment
    spec:
      containers:
        - name: postgres-container
          image: {{ .Values.postgres.imageTag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-secret
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: postgres-pv-storage
              mountPath: /var/lib/postgresql/data
      nodeSelector:
        cloud.google.com/gke-nodepool: {{ .Values.postgres.nodePoolName }}
      volumes:
        - name: postgres-pv-storage
          persistentVolumeClaim:
            claimName: postgres-volume-claim