apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
  namespace: {{ .Release.Namespace }}
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOncePod
  hostPath:
    path: /mnt/data