apiVersion: v1
kind: Secret
metadata:
  name: infinispan-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: infinispan-secret
type: Opaque
stringData:
  ISPN_MONITOR_USERNAME: ${infinispan.monitor.username}
  ISPN_MONITOR_PASSWORD: ${infinispan.monitor.password}
  ISPN_DEVELOPER_USERNAME: ${infinispan.developer.username}
  ISPN_DEVELOPER_PASSWORD: ${infinispan.developer.password}
  ISPN_OBSERVER_USERNAME: ${infinispan.observer.username}
  ISPN_OBSERVER_PASSWORD: ${infinispan.observer.password}
  ISPN_KEYCLOAK_USERNAME: ${infinispan.keycloak.username}
  ISPN_KEYCLOAK_PASSWORD: ${infinispan.keycloak.password}