
# TODO This does not need to be an openjdk image.  We only need to mount a folder
FROM us-west1-docker.pkg.dev/keycloak-infinispan-poc/infinispan-poc-repo/ubi8/openjdk-17-runtime:1.18-1 as builder

COPY themes/ /themes
